### ISSUE TITLE
Stop/Start vs Restart

### ISSUE THREAD

**Issue by robertpitt** [chriswessels/meteor-deployment-manager#5]
Hey guys.

Noticed a small issue when setting up MDM on the server, it seems the client calls the `restart meteor` command which can fail a lot of the time due to the service not in a running state.

My proposal is either run `stop` then `start`, or add a `status` command to check to see the state of the process before choosing `restart` or `start`.

**Comment by jf1603** [comment]
+1
Maybe an automatic restart should be avoided as you could "manually" call ````mdm stop```` before, and ````mdm start```` afterwards.

**Comment by chriswessels** [comment]
Thanks to @jf1603 for the fix in PR #9!
